# Generated by Django 5.0.4 on 2024-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('ContactNo', models.CharField(max_length=20)),
                ('EmailId', models.EmailField(max_length=255)),
                ('Salary', models.IntegerField()),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('ContactNo', models.CharField(max_length=20)),
                ('EmailId', models.EmailField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('Message', models.TextField()),
                ('Pic', models.ImageField(upload_to='media')),
                ('Enquiry_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('ContactNo', models.CharField(max_length=20)),
                ('RollNo', models.IntegerField()),
                ('EmailId', models.EmailField(max_length=255)),
                ('DOB', models.DateField()),
                ('CourseName', models.CharField(max_length=100)),
                ('CityName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Pincode', models.IntegerField()),
                ('FatherName', models.CharField(max_length=255)),
                ('MotherName', models.CharField(max_length=255)),
            ],
        ),
    ]
