# Generated by Django 5.0.4 on 2024-04-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_enquiry_dob_enquiry_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='userid',
        ),
    ]
