# Generated by Django 5.0.4 on 2024-04-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('Producttitle', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='')),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salesprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Quanity', models.IntegerField()),
                ('Description', models.TextField()),
                ('Status', models.BooleanField()),
                ('Catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('Subcatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory')),
            ],
        ),
    ]
