# Generated by Django 5.0.4 on 2024-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_usercart_entrydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
