# Generated by Django 5.0.4 on 2024-05-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_usercart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundimage', models.ImageField(upload_to='')),
                ('sliderimage', models.ImageField(upload_to='')),
                ('sliderheading', models.CharField(max_length=255)),
                ('slidercontent', models.TextField()),
            ],
        ),
    ]
