# Generated by Django 5.0.4 on 2024-05-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='address2',
        ),
        migrations.AddField(
            model_name='checkout',
            name='addline1',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='checkout',
            name='addline2',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='checkout',
            name='contact',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
