# Generated by Django 5.0.4 on 2024-05-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_ordereditems_userid_alter_ordereditems_cartid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='cartid',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='pids',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
